# Usa la imagen base de Python proporcionada por Microsoft
FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
# Instala las dependencias de Python con pip
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&apt-get install -y nodejs ffmpeg
# Actualiza el sistema e instala Node.js

# Otras configuraciones adicionales que desees agregar pueden ir aquí
